<?php
/**
 * @file
 * Query Arguments To URL install file.
 */

/**
 * Implements hook_uninstall().
 */
function query_parameters_to_url_uninstall() {
  // Load the module file, so we get the constant names and functions.
  drupal_load('module', 'query_parameters_to_url');

  variable_del(QUERY_PARAMETERS_TO_URL_ENABLED);
  variable_del(QUERY_PARAMETERS_TO_URL_HOOKS_ENABLED);
  variable_del(QUERY_PARAMETERS_TO_URL_URL_AND_QUERY_DELIMITER);
  variable_del(QUERY_PARAMETERS_TO_URL_QUERY_VALUE_DELIMITER);
  variable_del(QUERY_PARAMETERS_TO_URL_QUERY_NESTED_KEY_DELIMITER);
  variable_del(QUERY_PARAMETERS_TO_URL_QUERY_NESTED_VALUES_DELIMITER);
  variable_del(QUERY_PARAMETERS_TO_URL_PATH_REG_EXP);
}